backend:
  name: github
  repo: mvahedii/frontcamp

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Summary, name: summary, widget: string }
          - { label: Intro text, name: intro, widget: text }
          - { label: Image, name: image, widget: image }
          - label: "Time to Read"
            name: "time"
            widget: "number"
            default: 2
            valueType: "int"
            min: 1
            max: 30
            step: 1
